### ISSUE TITLE
Is it possible to relicense the remote API bindings under Apache or EPL or MPL or any other permissive license?

### ISSUE THREAD

**Issue by berezovskyi** [CoppeliaRobotics/remoteApiBindings#2]
The reason is that we are building an open-source research project that is Apache2 licensed. We are not modifying or redistributing VREP itself in any way. I thought the license would be similar to https://github.com/CoppeliaRobotics/v_repExtBlueZero/blob/master/license.txt for external API libraries. Would it be possible to relicense the repo, please?

**Comment by berezovskyi** [comment]
I deeply apologise, I was under impression that the bindings were still GPL after looking at https://github.com/Troxid/vrep-api-scala/blob/4704fcec445bd60da945fd50d035b1be7bed562b/src/main/java/coppelia/remoteApi.java and not fully realising they were out of date.

I, however, tried to understand the license of the files in this repo and I could not determine it to be any of the OSI approved licenses (https://opensource.org/licenses), which still represents a problem for relying on them in an Apache-licensed project.

Is it possible for you to relicense the bindings under any of http://www.apache.org/legal/resolved.html#category-a or http://www.apache.org/legal/resolved.html#category-b, please? I can make a PR with adding a proper LICENSE file to the repo root and an appropriate header to each source file if you are interested in doing that.

**Comment by Coppelia** [comment]
Hello,
didn't realize that a too permissive and "non-standard" license could be a source of problem because of non-OSI compliancy. But switching to a BSD License 2.0 is probably smarter for everyone. Will be done

**Comment by berezovskyi** [comment]
That would be perfect, thank you so much!

**Comment by berezovskyi** [comment]
Thanks, closing.
