### ISSUE TITLE
v-rep remote API usage in BSD-licensed code

### ISSUE THREAD

**Issue by bergercookie** [CoppeliaRobotics/remoteApiBindings#3]
I'm trying to utilise V-REP to provide simulation capabilities for (some of) the currently available MRPT algorithms. [MRPT](https://github.com/MRPT/mrpt) is a project licensed under BSD. V-REP is dual-licensed (commercial and GPL) as described [here](http://www.coppeliarobotics.com/helpFiles/en/licensing.htm).

It seems that the remoteApiBindings though are licensed differently than the core V-REP project. Does this mean that the remote API can be used directly in BSD-code. For example can a snippet like the following be published under the BSD license?

```
<BSD Licensed file>


#define NON_MATLAB_PARSING
#define MAX_EXT_API_CONNECTIONS 255
#define DO_NOT_USE_SHARED_MEMORY

#include <extApi.h>
#include <extApi.c>
#include <extApiPlatform.h>
#include <extApiPlatform.c>

int main(int argc, char *argv[])
{
        ...
	simxStart((simxChar*)"127.0.0.1",19999,true,true,2000,5);
	return 0;
}

```

**Comment by Coppelia** [comment]
This is no problem and perfectly ok. See also my answer on the forum
